# Import the data

In [73]:
import pandas as pd
import numpy as np

data_URL = "./Data/CarPrice_Assignment.csv"

data = pd.read_csv(data_URL, index_col=0)

data.head()

,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
car_ID,,,,,,,,,,,,,,,,,,,,,
1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,176.6,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,176.6,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

# Transforming Categorical Features

In [76]:
data.select_dtypes(include="object").columns

Index(['CarName', 'fueltype', 'aspiration', 'doornumber', 'carbody',
       'drivewheel', 'enginelocation', 'enginetype', 'cylindernumber',
       'fuelsystem'],
      dtype='object')

In [86]:
data["fueltype"].unique()
data["fueltype"].value_counts()
data['fueltype_gas'] = np.where(data["fueltype"] == "gas", 1, 0)
data['fueltype_diesel'] = np.where(data["fueltype"] == "diesel", 1, 0)

data["aspiration"].unique()
data["aspiration"].value_counts()
data['aspiration_std'] = np.where(data["aspiration"] == "std", 1, 0)
data['aspiration_turbo'] = np.where(data["aspiration"] == "turbo", 1, 0)

data["doornumber"].unique()
data["doornumber"].value_counts()
data['doornumber_two'] = np.where(data["doornumber"] == "two", 1, 0)
data['doornumber_four'] = np.where(data["doornumber"] == "four", 1, 0)

data["carbody"].unique()
data["carbody"].value_counts()
data['carbody_sedan'] = np.where(data["carbody"] == "sedan", 1, 0)
data['carbody_hatchback'] = np.where(data["carbody"] == "hatchback", 1, 0)
data['carbody_wagon'] = np.where(data["carbody"] == "wagon", 1, 0)
data['carbody_hardtop'] = np.where(data["carbody"] == "hardtop", 1, 0)
data['carbody_convertible'] = np.where(data["carbody"] == "convertible", 1, 0)

data["drivewheel"].unique()
data["drivewheel"].value_counts()
data['drivewheel_fwd'] = np.where(data["drivewheel"] == "fwd", 1, 0)
data['drivewheel_rwd'] = np.where(data["drivewheel"] == "rwd", 1, 0)
data['drivewheel_4wd'] = np.where(data["drivewheel"] == "4wd", 1, 0)

data["enginelocation"].unique()
data["enginelocation"].value_counts()
data['enginelocation_front'] = np.where(data["enginelocation"] == "front", 1, 0)
data['enginelocation_rear'] = np.where(data["enginelocation"] == "rear", 1, 0)

data["enginetype"].unique()
data["enginetype"].value_counts()
data['enginetype_ohc'] = np.where(data["enginetype"] == "ohc", 1, 0)
data['enginetype_ohcf'] = np.where(data["enginetype"] == "ohcf", 1, 0)
data['enginetype_ohcv'] = np.where(data["enginetype"] == "ohcv", 1, 0)
data['enginetype_dohc'] = np.where(data["enginetype"] == "dohc", 1, 0)
data['enginetype_l'] = np.where(data["enginetype"] == "l", 1, 0)
data['enginetype_rotor'] = np.where(data["enginetype"] == "rotor", 1, 0)
data['enginetype_dohcv'] = np.where(data["enginetype"] == "dohcv", 1, 0)

data["cylindernumber"].unique()
data["cylindernumber"].value_counts()
data['cylindernumber_two'] = np.where(data["cylindernumber"] == "two", 1, 0)
data['cylindernumber_three'] = np.where(data["cylindernumber"] == "three", 1, 0)
data['cylindernumber_four'] = np.where(data["cylindernumber"] == "four", 1, 0)
data['cylindernumber_five'] = np.where(data["cylindernumber"] == "five", 1, 0)
data['cylindernumber_six'] = np.where(data["cylindernumber"] == "six", 1, 0)
data['cylindernumber_eight'] = np.where(data["cylindernumber"] == "eight", 1, 0)
data['cylindernumber_twelve'] = np.where(data["cylindernumber"] == "twelve", 1, 0)

data["fuelsystem"].unique()
data["fuelsystem"].value_counts()
data['fuelsystem_mpfi'] = np.where(data["fuelsystem"] == "mpfi", 1, 0)
data['fuelsystem_2bbl'] = np.where(data["fuelsystem"] == "2bbl", 1, 0)
data['fuelsystem_idi'] = np.where(data["fuelsystem"] == "idi", 1, 0)
data['fuelsystem_1bbl'] = np.where(data["fuelsystem"] == "1bbl", 1, 0)
data['fuelsystem_spdi'] = np.where(data["fuelsystem"] == "spdi", 1, 0)
data['fuelsystem_4bbl'] = np.where(data["fuelsystem"] == "4bbl", 1, 0)
data['fuelsystem_mfi'] = np.where(data["fuelsystem"] == "mfi", 1, 0)
data['fuelsystem_spfi'] = np.where(data["fuelsystem"] == "spfi", 1, 0)

front    202
rear       3
Name: enginelocation, dtype: int64

In [102]:
data = data.drop(columns=data.select_dtypes(include="object").columns)

In [103]:
data.head()

,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,...,cylindernumber_eight,cylindernumber_twelve,fuelsystem_mpfi,fuelsystem_2bbl,fuelsystem_idi,fuelsystem_1bbl,fuelsystem_spdi,fuelsystem_4bbl,fuelsystem_mfi,fuelsystem_spfi
car_ID,,,,,,,,,,,,,,,,,,,,,
1,3,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,...,0,0,1,0,0,0,0,0,0,0
2,3,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,...,0,0,1,0,0,0,0,0,0,0
3,1,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,...,0,0,1,0,0,0,0,0,0,0
4,2,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,...,0,0,1,0,0,0,0,0,0,0
5,2,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,8.0,...,0,0,1,0,0,0,0,0,0,0

# Removing Nan or Null value

In [110]:
data.isnull().values.any()

False

# Saving Cleaned Data

In [107]:
cleaned_data_URL = "./Cleaned Data/Data.csv"

data.to_csv(cleaned_data_URL)